<a href="https://colab.research.google.com/github/vshanjaisriram8870/guvirestaurant-analysis/blob/main/shan_project_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
ds= pd.read_csv("/content/Uber_Eats_data.csv")

In [ ]:
print(ds.shape)

(23193, 13)

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

In [ ]:
ds.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [ ]:
print(ds.columns)

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [ ]:
print (ds.isna().sum())# for nan value in my dataset print

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [ ]:
ds.isnull().sum() # for null values

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [ ]:
ds = ds.drop_duplicates() # (to find out the duplicate values in dataset)

In [ ]:
print("Before:", ds.shape)# (but  ouptut cant shows,  so we use this pieace of code before and after)
ds = ds.drop_duplicates()
print("After:", ds.shape)

Before: (23158, 13)
After: (23158, 13)

In [ ]:
print(ds.duplicated().sum()) # (its show the sum of duplicate values in dataset)

0

In [ ]:
(ds == "").sum() #(for empty string)

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [ ]:
ds['name']

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
23188                                   Izakaya Gastro Pub
23189          M Bar - Bengaluru Marriott Hotel Whitefield
23190                               Keys Cafe - Keys Hotel
23191                                              Bhagini
23192    Chime - Sheraton Grand Bengaluru Whitefield Ho...
Name: name, Length: 23158, dtype: object

In [ ]:
ds['name'].isnull().sum()

np.int64(0)

In [ ]:
ds['online_order']

0        Yes
1        Yes
2        Yes
3         No
4         No
        ...
23188    Yes
23189     No
23190     No
23191     No
23192     No
Name: online_order, Length: 23158, dtype: object

In [ ]:
ds['online_order'].isnull().sum()

np.int64(0)

In [ ]:
ds['online_order'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
ds['book_table']

0        Yes
1         No
2         No
3         No
4         No
        ...
23188    Yes
23189     No
23190     No
23191     No
23192    Yes
Name: book_table, Length: 23158, dtype: object

In [ ]:
ds['book_table'].isnull().sum()

np.int64(0)

In [ ]:
ds['book_table'].value_counts()

book_table
No     17057
Yes     6101
Name: count, dtype: int64

In [ ]:
ds['book_table'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
ds['rate'].value_counts()

rate
3.9/5     1686
3.9 /5    1547
4.0/5     1467
4.1/5     1396
4.0 /5    1390
          ...
2.2 /5       7
2.0 /5       7
2.0/5        4
1.8 /5       3
1.8/5        2
Name: count, Length: 63, dtype: int64

In [ ]:
ds['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', 'NEW', '2.4/5', '2.2/5', '2.3/5',
       '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5',
       '2.7 /5', '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5',
       '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5',
       '3.3 /5', '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5',
       '3.5 /5', '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [ ]:
ds['rate'].isnull().sum()

np.int64(0)

In [ ]:
ds['rate'] = ds['rate'].astype(str).str.replace('/5', '')
print(ds['rate'])

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23158, dtype: object

In [ ]:
ds = ds[ds['rate'] != 'NEW']

ds = ds[ds['rate'] != '-']

In [ ]:
ds['rate']

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23012, dtype: object

In [ ]:
ds['rate'] = ds['rate'].astype(float)

In [ ]:
(ds['rate'].dtype)

dtype('float64')

In [ ]:
(ds['votes'].dtype)

dtype('int64')

In [ ]:
ds['votes'].isnull().sum()

np.int64(0)

In [ ]:
ds['phone']

0          080 42297555\r\n+91 9743772233
1                            080 41714161
2                          +91 9663487993
3                          +91 9620009302
4        +91 8026612447\r\n+91 9901210005
                       ...
23188      +91 7625087121\n+91 8050587483
23189                        080 49435000
23190        080 39451000\n+91 8884038484
23191                        080 65951222
23192                        080 49652769
Name: phone, Length: 23012, dtype: object

In [ ]:
ds['phone'].value_counts()

phone
080 33994444                            57
+91 7700020020                          54
+91 8880141000                          33
080 49994999                            33
+91 7676764422                          32
                                        ..
080 41460555\r\r\r\n080 41460666         1
+91 9742293475\r\r\r\n080 65650566       1
+91 9945640717\r\r\r\n+91 9886484223     1
+91 9606485642\r\r\r\n+91 9606485641     1
080 25533344\r\r\r\n+91 7019629831       1
Name: count, Length: 6780, dtype: int64

In [ ]:
ds.drop('phone', axis=1, inplace=True)

In [ ]:
print(ds.columns)

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [ ]:
(ds['location'].dtype)  #o is object

dtype('O')

In [ ]:
ds['location'].isnull().sum()

np.int64(0)

In [ ]:
ds['rest_type']

0              Casual Dining
1              Casual Dining
2        Cafe, Casual Dining
3                Quick Bites
4              Casual Dining
                ...
23188     Bar, Casual Dining
23189       Fine Dining, Bar
23190     Casual Dining, Bar
23191     Casual Dining, Bar
23192                    Bar
Name: rest_type, Length: 23012, dtype: object

In [ ]:
ds['rest_type'].isnull().sum()

np.int64(0)

In [ ]:
ds['rest_type'].value_counts()

rest_type
Casual Dining                7291
Quick Bites                  5219
Cafe                         2319
Dessert Parlor               1073
Casual Dining, Bar            975
                             ...
Fine Dining, Microbrewery       5
Club, Casual Dining             4
Dessert Parlor, Kiosk           2
Dhaba                           1
Food Court, Casual Dining       1
Name: count, Length: 73, dtype: int64

In [ ]:
ds['dish_liked'].isnull().sum()

np.int64(0)

In [ ]:
ds['dish_liked'].value_counts()

dish_liked
Biryani                                                                                             179
Friendly Staff                                                                                       68
Waffles                                                                                              67
Chicken Biryani                                                                                      66
Masala Dosa                                                                                          56
                                                                                                   ...
Pasta, Creme Brulee, Tiramisu, Bbq Chicken Pizza, Steak, Salads, Wine                                 1
Cocktails, Panna Cotta, Lamb Pizza, Pita Bread                                                        1
Murgh Platter, Dessert Platter, Chicken Sizzler, Tiramisu, Lobster, Mocktails, Vegetable Biryani      1
Coffee, Raj Kachori, Idli, Vada, Tea, Masala Dosa, Chaat                                              1
Masala Dosa, Filter Coffee, Curd Rice                                                                 1
Name: count, Length: 5145, dtype: int64

In [ ]:
ds['dish_liked'].isnull().sum()

np.int64(0)

In [ ]:
ds['dish_liked'] = ds['dish_liked'].str.strip()

In [ ]:
ds['dish_liked'].unique() # it shows unique values in my data set

array(['Pasta, Lunch Buffet, Masala Papad, Paneer Lajawab, Tomato Shorba, Dum Biryani, Sweet Corn Soup',
       'Momos, Lunch Buffet, Chocolate Nirvana, Thai Green Curry, Paneer Tikka, Dum Biryani, Chicken Biryani',
       'Churros, Cannelloni, Minestrone Soup, Hot Chocolate, Pink Sauce Pasta, Salsa, Veg Supreme Pizza',
       ...,
       'Noodles, Chicken Noodle, Momos, American Chopsuey, Salad, Manchow Soup, Manchurian',
       'Chicken Quesadilla, Naan, Breakfast Buffet, Cheesecake, Cocktails, Lunch Buffet, Biryani',
       'Biryani, Andhra Meal'], dtype=object)

In [ ]:
ds['dish_liked'].nunique()  # to how many unique in my dataset

5145

In [ ]:
ds['cuisines']

0                     North Indian, Mughlai, Chinese
1                        Chinese, North Indian, Thai
2                             Cafe, Mexican, Italian
3                         South Indian, North Indian
4                           North Indian, Rajasthani
                            ...
23188       North Indian, Continental, Mediterranean
23189                                    Finger Food
23190             Chinese, Continental, North Indian
23191    Andhra, South Indian, Chinese, North Indian
23192                                    Finger Food
Name: cuisines, Length: 23012, dtype: object

In [ ]:
ds['cuisines'].isnull().sum()

np.int64(0)

In [ ]:
ds['approx_cost(for two people)']

0          800
1          800
2          800
3          300
4          600
         ...
23188    1,200
23189    2,000
23190    1,200
23191      800
23192    2,500
Name: approx_cost(for two people), Length: 23012, dtype: object

In [ ]:
ds['approx_cost(for two people)'] = ds['approx_cost(for two people)'].str.replace(',', '')# to remove the comma replace

In [ ]:
ds['approx_cost(for two people)'] = ds['approx_cost(for two people)'].astype(int)# object to integer

In [ ]:
ds['approx_cost(for two people)']

0         800
1         800
2         800
3         300
4         600
         ...
23188    1200
23189    2000
23190    1200
23191     800
23192    2500
Name: approx_cost(for two people), Length: 23012, dtype: int64

In [ ]:
ds['approx_cost(for two people)'].isnull().sum()

np.int64(0)

In [ ]:
print(ds.columns)

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [ ]:
ds['listed_in(type)']

0               Buffet
1               Buffet
2               Buffet
3               Buffet
4               Buffet
             ...
23188    Pubs and bars
23189    Pubs and bars
23190    Pubs and bars
23191    Pubs and bars
23192    Pubs and bars
Name: listed_in(type), Length: 23012, dtype: object

In [ ]:
ds['listed_in(type)'].isnull().sum()

np.int64(0)

In [ ]:
ds['listed_in(city)']

0        Banashankari
1        Banashankari
2        Banashankari
3        Banashankari
4        Banashankari
             ...
23188      Whitefield
23189      Whitefield
23190      Whitefield
23191      Whitefield
23192      Whitefield
Name: listed_in(city), Length: 23012, dtype: object

In [ ]:
ds['listed_in(city)'].isnull().sum()

np.int64(0)

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23012 entries, 0 to 23192
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23012 non-null  object
 1   online_order                 23012 non-null  object
 2   book_table                   23012 non-null  object
 3   rate                         23012 non-null  float64
 4   votes                        23012 non-null  int64
 5   location                     23012 non-null  object
 6   rest_type                    23012 non-null  object
 7   dish_liked                   23012 non-null  object
 8   cuisines                     23012 non-null  object
 9   approx_cost(for two people)  23012 non-null  int64
 10  listed_in(type)              23012 non-null  object
 11  listed_in(city)              23012 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

In [ ]:
ds.head()

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [ ]:
ds.describe()

               rate         votes  approx_cost(for two people)
count  23012.000000  23012.000000                 23012.000000
mean       3.904002    604.098688                   753.704154
std        0.426388   1116.738081                   521.191287
min        1.800000      0.000000                    40.000000
25%        3.800000    103.000000                   400.000000
50%        4.000000    224.000000                   600.000000
75%        4.200000    590.000000                  1000.000000
max        4.900000  16832.000000                  6000.000000

In [ ]:
ds.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [ ]:
ds.duplicated().sum()

np.int64(7)

In [ ]:
!pip install ftfy

Collecting ftfy
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy) (0.6.0)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.1 MB/s eta 0:00:00
Installing collected packages: ftfy
Successfully installed ftfy-6.3.1

In [ ]:
import ftfy

In [ ]:
import ftfy
ds['name'] = ds['name'].apply(ftfy.fix_text)

In [ ]:
ds['name'].head(10)

0                    Jalsa
1           Spice Elephant
2          San Churro Cafe
3    Addhuri Udupi Bhojana
4            Grand Village
5          Timepass Dinner
6                   Onesta
7           Penthouse Cafe
8                Smacznego
9      Café Down The Alley
Name: name, dtype: object

In [ ]:
ds.to_csv("cleaned_uber_eats.csv", index=False, encoding='utf-8-sig')

In [ ]:
df = pd.read_json("/content/orders.json")   # cleaning json file

In [ ]:
print("order jason(rows,columns):",df.shape)
print(df.head())

order jason(rows,columns): (25000, 6)
                               order_id          restaurant_name  order_date  \
0  8174c2af-07a4-4837-9068-1169d963e36e           TBC Sky Lounge  2025-05-06
1  0f9ddb57-4632-4a9f-9afe-1d2e41b94e32  KC Das - Sweet Paradise  2026-01-08
2  099deda6-8c53-41cb-abf8-00126e6b2643        Hotel Kadamba Veg  2026-01-22
3  94a6ba27-d6ef-4d10-a026-ac0c0afa8505            Cafe Srinidhi  2025-11-10
4  216f3ec7-80a9-4d95-872f-715c37163b6d                   Pebble  2025-12-22

   order_value discount_used payment_method
0       201.87            No           Card
1      1392.27            No           Cash
2      1358.35           Yes            UPI
3       782.37            No            UPI
4      1551.09           Yes            UPI

In [ ]:
print("\norder_details information:")
print(df.info())

order_details information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  object
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.1+ MB
None

In [ ]:
print("\nNULL VALUES:")
print(df.isnull().sum())

NULL VALUES:
order_id           0
restaurant_name    0
order_date         0
order_value        0
discount_used      0
payment_method     0
dtype: int64

In [ ]:
print("\nDuplicate Order IDs:", df['order_id'].duplicated().sum())

Duplicate Order IDs: 0

In [ ]:
df = df.drop_duplicates(subset='order_id')# just cleaning cloummn based duplicate

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [ ]:
df['order_value'] = pd.to_numeric(df['order_value'], errors='coerce')

In [ ]:
df['restaurant_name'] = df['restaurant_name'].str.strip()

In [ ]:
df['payment_method'] = df['payment_method'].str.strip()

In [ ]:
df['discount_used'] = df['discount_used'].astype(str).str.strip()

In [ ]:
df['discount_used'] = df['discount_used'].str.strip()

In [ ]:
print("\nOrder Value Stats:")
print(df['order_value'].describe())

Order Value Stats:
count    25000.000000
mean       986.081873
std        472.948544
min        150.050000
25%        589.602500
50%        966.475000
75%       1344.772500
max       1999.840000
Name: order_value, dtype: float64

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
print("\nFinal Shape:", df.shape)
print("\nCleaned Data Sample:")
print(df.head())

Final Shape: (25000, 6)

Cleaned Data Sample:
                               order_id          restaurant_name order_date  \
0  8174c2af-07a4-4837-9068-1169d963e36e           TBC Sky Lounge 2025-05-06
1  0f9ddb57-4632-4a9f-9afe-1d2e41b94e32  KC Das - Sweet Paradise 2026-01-08
2  099deda6-8c53-41cb-abf8-00126e6b2643        Hotel Kadamba Veg 2026-01-22
3  94a6ba27-d6ef-4d10-a026-ac0c0afa8505            Cafe Srinidhi 2025-11-10
4  216f3ec7-80a9-4d95-872f-715c37163b6d                   Pebble 2025-12-22

   order_value discount_used payment_method
0       201.87            No           Card
1      1392.27            No           Cash
2      1358.35           Yes            UPI
3       782.37            No            UPI
4      1551.09           Yes            UPI

In [ ]:
df.to_csv("clean_orders.csv", index=False)

In [ ]:
df = pd.read_csv("/content/clean_orders (1).csv")

print(df.head())

                               order_id          restaurant_name  order_date  \
0  8174c2af-07a4-4837-9068-1169d963e36e           TBC Sky Lounge  2025-05-06
1  0f9ddb57-4632-4a9f-9afe-1d2e41b94e32  KC Das - Sweet Paradise  2026-01-08
2  099deda6-8c53-41cb-abf8-00126e6b2643        Hotel Kadamba Veg  2026-01-22
3  94a6ba27-d6ef-4d10-a026-ac0c0afa8505            Cafe Srinidhi  2025-11-10
4  216f3ec7-80a9-4d95-872f-715c37163b6d                   Pebble  2025-12-22

   order_value  discount_used payment_method
0       201.87              0           Card
1      1392.27              0           Cash
2      1358.35              1            Upi
3       782.37              0            Upi
4      1551.09              1            Upi

In [ ]:
print(df.columns)
print(df.info())

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  object
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  int64
 5   payment_method   25000 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ MB
None

In [ ]:
df.columns = df.columns.str.strip()  # remove spaces
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace(r"[()]", "", regex=True)

print(df.columns)

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

In [ ]:
df = df.fillna("")